apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: central-user-secrets-manager
spec:
  provider:
    aws:
      service: SecretsManager
      region: eu-west-2
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: central-awssm-secret
            namespace: external-secrets
            key: access-key
          secretAccessKeySecretRef:
            name: central-awssm-secret
            namespace: external-secrets
            key: secret-access-key