apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: ${name}
  namespace: es-${name}
spec:
  version: 8.8.1
  http:
    service:
      metadata:
        annotations:
          cloud.google.com/neg: '{"ingress": true}'
          konghq.com/protocol: https
  nodeSets:
  - name: default
    count: ${nodesets}
    podTemplate:
      spec:
        initContainers:
        - name: sysctl
          securityContext:
            privileged: true
            runAsUser: 0
          command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data # Do not change this name unless you set up a volume mount for the data path.
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: ${storage_size}
        storageClassName: ${storage_class}
